apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.synthesized.name }}-pvc
spec:
  storageClassName: {{ .Values.synthesized.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.synthesized.storageSize }}
