apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.synthesized.name }}-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.synthesized.storageSize }}
